<a href="https://colab.research.google.com/github/kim-minsol/MachineLearning2021-study/blob/main/DeepLearning_(Basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy 이용한 인공신경망 데이터 이해

In [ ]:
import numpy as np

"""
1. numpy 라이브러리를 이용하여 아래 속성 정보를 가지는 스칼라 텐서 객체 생성
-------- [출력 결과] --------
*******1. 스칼라(0D 텐서)*******
차원        :  0
크기        :  ()
데이터 타입 :  int64
--------------------------
"""
d0_tensor = np.array(2)

# 생성한 스칼라 텐서 객체 속성 정보 출력
print('*******1. 스칼라(0D 텐서)*******')
print('차원        : ', d0_tensor.ndim)
print('크기        : ', d0_tensor.shape)
print('데이터 타입 : ', d0_tensor.dtype)


"""
2. numpy 라이브러리를 이용하여 아래 속성 정보를 가지는 백터 텐서 객체 생성
-------- [출력 결과] --------
*******2. 벡터(1D 텐서)*******
차원        :  1
크기        :  (5,)
데이터 타입 :  float64
--------------------------
"""
d1_tensor = np.array([1.,2.,3.,4.,5.])

# 생성한 벡터 텐서 객체 속성 정보 출력
print('\n*******2. 벡터(1D 텐서)*******')
print('차원        : ', d1_tensor.ndim)
print('크기        : ', d1_tensor.shape)
print('데이터 타입 : ', d1_tensor.dtype)


"""
3. numpy 라이브러리를 이용하여 아래 속성 정보를 가지는 행렬 텐서 객체 생성
-------- [출력 결과] --------
*******3. 행렬(2D 텐서)*******
차원        :  2
크기        :  (3, 2)
데이터 타입 :  int64
--------------------------
"""
d2_tensor = np.array([[1,2],
                      [3,4],
                      [5,6]])

# 생성한 행렬 텐서 객체 속성 정보 출력
print('\n*******3. 행렬(2D 텐서)*******')
print('차원        : ', d2_tensor.ndim)
print('크기        : ', d2_tensor.shape)
print('데이터 타입 : ', d2_tensor.dtype)


"""
4. numpy 라이브러리를 이용하여 아래 속성 정보를 가지는 3D 텐서 객체 생성
-------- [출력 결과] --------
*******4. 3D 텐서*******
차원        :  3
크기        :  (2, 3, 1)
데이터 타입 :  int64
--------------------------
"""
d3_tensor = np.array([[[1],
                       [2],
                       [3]],
                      [[4],
                       [5],
                       [6]]])

# 생성한 3D 텐서 객체 속성 정보 출력
print('\n*******4. 3D 텐서*******')
print('차원        : ', d3_tensor.ndim)
print('크기        : ', d3_tensor.shape)
print('데이터 타입 : ', d3_tensor.dtype)
          

*******1. 스칼라(0D 텐서)*******
차원        :  0
크기        :  ()
데이터 타입 :  int64

*******2. 벡터(1D 텐서)*******
차원        :  1
크기        :  (5,)
데이터 타입 :  float64

*******3. 행렬(2D 텐서)*******
차원        :  2
크기        :  (3, 2)
데이터 타입 :  int64

*******4. 3D 텐서*******
차원        :  3
크기        :  (2, 3, 1)
데이터 타입 :  int64


TensorFlow 2.0 를 이용한 인공신경망 데이터 이해

In [ ]:
import numpy as np
import tensorflow as tf

"""
1. tensorflow 라이브러리를 이용하여 아래 속성 정보를 가지는 상수 텐서 객체 생성 및 속성 정보 출력
-------- [출력 결과] --------
*******1. 상수 텐서 객체*******
차원        :  3
크기        :  (3, 1, 2)
데이터 타입 :  <dtype: 'int32'>
--------------------------
"""

# 상수 텐서 객체 생성
d3_tensor = tf.constant([[[1,2]],
                         [[4,5]],
                         [[6,7]]])

# 생성한 상수 텐서 객체 속성 정보 출력
print('*******1. 상수 텐서 객체*******')
print('차원        : ', d3_tensor.ndim)
print('크기        : ', d3_tensor.shape)
print('데이터 타입 : ', d3_tensor.dtype)

"""
2. 상수 텐서 객체의 값(ndarray) 복사하여 속성 정보 출력
-------- [출력 결과] --------
*******2. ndarray 객체*******
차원        :  3
크기        :  (3, 1, 2)
데이터 타입 :  int32
--------------------------
"""

# 상수 텐서에서 .numpy() 메서드 이용하여 numpy ndarray 객체 복사
np_d3_tensor = d3_tensor.numpy()
np_d3_tensor = np_d3_tensor.astype(np.int32)

# 복사한 ndarray 객체의 속성 정보 출력
print('\n*******2. ndarray 객체*******')
print('차원        : ', np_d3_tensor.ndim)
print('크기        : ', np_d3_tensor.shape)
print('데이터 타입 : ', np_d3_tensor.dtype)

"""
3. tensorflow 라이브러리를 이용하여 아래 속성 정보를 가지는 변수 텐서 객체 생성 및 속성 정보 출력
-------- [출력 결과] --------
*******3. 변수 텐서 객체*******
크기        :  (2, 3, 1)
데이터 타입 :  <dtype: 'int32'>
--------------------------
"""

# 형태의 변수 텐서 객체 생성
d3_np_tensor = np.array([[[1],
                           [2],
                           [3]],
                          [[4],
                           [5],
                           [6]]])
d3_np_tensor = d3_np_tensor.astype(np.int32)

d3_var_tensor = tf.Variable(d3_np_tensor)

print('\n*******3. 변수 텐서 객체*******')
print('크기        : ', d3_var_tensor.shape)
print('데이터 타입 : ', d3_var_tensor.dtype)

*******1. 상수 텐서 객체*******
차원        :  3
크기        :  (3, 1, 2)
데이터 타입 :  <dtype: 'int32'>

*******2. ndarray 객체*******
차원        :  3
크기        :  (3, 1, 2)
데이터 타입 :  int32

*******3. 변수 텐서 객체*******
크기        :  (2, 3, 1)
데이터 타입 :  <dtype: 'int32'>


Tensorflow 연산자 이해

In [ ]:
import tensorflow as tf
import numpy as np

# (2, 3) 형태의 상수 텐서 'tensor_a' 생성
tensor_a = tf.constant([[1., 2., 3.],
                        [4., 5., 6.]])

"""
1. tensorflow 연산자를 이용해 'tensor_a' 텐서에 지수 연산을 적용
-------- [출력 결과] --------
*******1. 지수연산*******
[[ *.** *.** *.** ]
 [ *.** *.** *.** ]]
--------------------------
"""

# tf.math 모듈의 지수(exponential)함수를 이용해 'tensor_a' 텐서에 지수 연산 적용
print('*******1. 지수연산*******')

tensor_exp = tf.math.square(tensor_a)
print(np.round(tensor_exp, 2))


"""
2. tensorflow 연산자를 이용해 'tensor_a'의 axis 0 을 기준으로 최대값 선택
-------- [출력 결과] --------
*******2. axis 0 기준 최대값*******
[ * * ]
--------------------------
"""

# tf.math 모듈의 함수를 이용해 'tensor_a'의 axis 0 기준 최대값 선택
print('\n*******2. axis 0 기준 최대값*******')

tensor_axis_max = tensor_a.numpy()
tensor_axis_max = tensor_axis_max.max(axis=0)

print(tensor_axis_max)


"""
3. tensorflow 연산자를 이용해 z = (x+y)^2 계산식에서 x 값이 z 값에 미치는 영향도(미분) 계산
-------- [출력 결과] --------
*******3. 'tensor_x' 값이 'tensor_z' 값에 미치는 영향도(미분 값)*******
[[*.**  *.**  *.**]
 [*.**  *.**  *.**]]
--------------------------
"""

tensor_x = tf.Variable([[1., 2., 3.],
                        [4., 5., 6.]])

tensor_y = tf.Variable([[7., 8., 9.],
                        [10., 11., 12.]])

print("\n*******3. 'tensor_x' 값이 'tensor_z' 값에 미치는 영향도(미분 값)*******")
with tf.GradientTape() as tape:
  # 텐서플로 연산자와 변수 텐서를 이용해 계산그래프 정의
  tensor_z = tf.square(tensor_x + tensor_y)
  
  # tape.gradient를 통해 tensor_x 가 tensor_z 에 미치는 영향도(미분 값)를 계산
  gradient_zx = tape.gradient(target=tensor_z, sources=tensor_x)
  
  # 계산된 영향도(미분 값) 확인
  print(np.round(gradient_zx, 2))


*******1. 지수연산*******
[[ 1.  4.  9.]
 [16. 25. 36.]]

*******2. axis 0 기준 최대값*******
[4. 5. 6.]

*******3. 'tensor_x' 값이 'tensor_z' 값에 미치는 영향도(미분 값)*******
[[16. 20. 24.]
 [28. 32. 36.]]


실습 : TensorFlow 2.0 을 이용한 퍼셉트론 구현


In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 파라미터 값(input 특성 개수, 퍼셉트론의 개수, 학습률) 설정
input_dim = 2
hidden_units = 1
learning_rate = 0.01

# 가중치(input 특성 : 2/ 퍼셉트론 : 1)
w = tf.Variable(tf.random.uniform(shape=(input_dim, hidden_units)))

# 편향(퍼셉트론 : 1)
b = tf.Variable(tf.zeros(shape=(hidden_units,)))

# 설계한 퍼셉트론 모델의 파라미터 확인(코드 제출시 주석 처리)
#print('*******퍼셉트론 모델의 초기 가중치*******')
#print(w)
#print('\n*******퍼셉트론 모델의 초기 편향*******')
#print(b)

# 퍼셉트론의 수학 모델 f(x*w + b) 구현
def predict(input):
  # x*w + b 연산 구현
  x = tf.matmul(input, w) + b
  # relu 활성화 함수 구현
  x = tf.maximum(0, x)
  return x

# loss(mse)
def mse_loss(labels, predictions):
  # MSE(Mean Square Error) 연산 구현
  loss = tf.reduce_mean(tf.square(labels - predictions))
  return loss

# train
def train(inputs, labels):
  with tf.GradientTape() as tape:
    # 퍼셉트론 모델을 예측값을 계산
    predictions = predict(inputs)
    # 모델의 예측값과 정답간의 에러를 loss 을 이용해 계산
    loss = mse_loss(labels, predictions)
    # 모델의 파라미터(w, b)가 loss 값에 미치는 영향도를 미분(오차역전파)을 통해 계산
    gradient_lw, gradient_lb = tape.gradient(loss,[w,b])
  # 경사하강법을 수행하여 모델의 파라미터(w, b) 업데이트
  w.assign(w-learning_rate * gradient_lw)
  b.assign(b-learning_rate * gradient_lb)
  return loss

# 퍼셉트론 모델 학습을 위한 OR Gate 데이터 생성
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]], dtype=np.float32)

labels = np.array([0, 1, 1, 1], dtype=np.float32)

# OR Gate 데이터를 차트로 확인(코드 제출시 주석 처리)
#plt.scatter(inputs[:, 0], inputs[:, 1], c=labels[:])
#plt.show()

# train 함수를 반복적으로 실행하여 퍼셉트론 모델을 학습
for epoch in range(100):
  # input 데이터와 label 데이터를 한 건씩 추출하여 train 함수에 전달
  for x, y in zip(inputs, labels):
    loss = train([x], [y])
  # 학습 중간에 loss 값의 변화 출력(코드 제출시 주석 처리)
  #if (epoch+1)%10 == 0:
    #print("Epoch {}: loss={}".format(epoch+1, float(loss)))

# 학습된 모델에 input 데이터 입력하여 예측결과 계산
predictions = predict(inputs)

# 모델의 예측결과를 차트로 확인(코드 제출시 주석 처리)
#plt.scatter(inputs[:, 0], inputs[:, 1], c=predictions[:]> 0.5)
#plt.show()

print('*******모델의 예측 결과*******')
print(predictions[:]> 0.5)

*******모델의 예측 결과*******
tf.Tensor(
[[False]
 [ True]
 [ True]
 [ True]], shape=(4, 1), dtype=bool)


Keras API 를 활용한 fashion-mnist 데이터셋 분류 실습

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
import matplotlib.pyplot as plt

"""* Step 1. Input tensor 와 Target tensor 준비(훈련데이터)"""

# label 데이터의 각 value 에 해당하는 class name 정보
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 수강생 작성 코드
# 1. import 한 fashion_mnist API를 이용하여 fashion_mnist 데이터 셋을 다운로드 받으세요
(train_images, train_labels), (test_images, test_labels)=fashion_mnist.load_data()


"""* Step 2. 데이터의 전처리 """

# 수강생 작성 코드
# 1. 3차원 형태(batch, hight, width)의 train, test feature 데이터를 2차원(batch, hight*width)으로 변경 하세요
# 2. feature 데이터를 [0, 1] 사이로 scailing을 수행하세요
train_images = train_images.reshape(60000, 784)
test_images = test_images.reshape(10000, 784)

from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(train_images)
train_images=mms.transform(train_images)

mms = MinMaxScaler()
mms.fit(test_images)
test_images=mms.transform(test_images)



# 수강생 작성 코드
# 1. 1차원 형태의(batch, ) class index 인 train, test label 데이터를
#    to_categorical API를 이용하여 one-hot-encoding 수행하여 2차원(batch, class_cnt) 으로 변경 하세요

from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)



"""* Step 3. DNN(MLP) 모델 디자인"""

# 수강생 작성 코드
# 1. Sequential API를 이용하여 fashion_mnist 데이터 셋을 분석 하기 위한 MLP 모델을 디자인 하세요
from tensorflow.keras import models, layers
model = models.Sequential()
model.add(layers.Dense(units=160, activation = 'relu', input_shape=(28*28,)))
model.add(layers.Dense(units=10, activation='softmax'))

model.summary()

"""* Step 4. 모델의 학습 정보 설정"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 compile 메서드를 이용하여 학습을 위한 정보들을 설정하세요
#   - optimizer
#   - loss : categorical_crossentropy 로 설정(label 데이터를 one-hot-encoding 하였기 때문)
#   - metrics : 체점 기준인 accuracy 로 설정

model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])


"""* Step 5. 모델에 input, target 데이터 연결 후 학습"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 fit 메서드를 이용하여 모델을 학습하세요
#   - fit 메서드의 verbose=2 로 설정 하세요

model.fit(x = train_images,
          y = train_labels,
          epochs = 30,
          batch_size = 40,
          validation_split = 0.2,
          verbose = 2)


"""* 모델 제출 """

# 학습된 모델을 제출하기 위한 코드 입니다. 수정하지 마세요
model.save('my_model.h5')

4423680/4422102 [==============================] - 0s 0us/step
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 160)               125600    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1610      
Total params: 127,210
Trainable params: 127,210
Non-trainable params: 0
_________________________________________________________________
Epoch 1/30
1200/1200 - 4s - loss: 0.5308 - accuracy: 0.8102 - val_loss: 0.4020 - val_accuracy: 0.8602
Epoch 2/30
1200/1200 - 3s - loss: 0.3862 - accuracy: 0.8611 - val_loss: 0.3881 - val_accuracy: 0.8658
Epoch 3/30
1200/1200 - 3s - loss: 0.3458 - accuracy: 0.8764 - val_loss: 0.3761 - val_accuracy: 0.8753
Epoch 4/30
1200/1200 - 3s - loss: 0.3267 - accuracy: 0.8828 - val_loss: 0.3620 - val_accuracy: 0.8749
Epoch 5/30
1200/1200 - 3s - loss: 0.3097 

자동차 연비 데이터셋 파일 다운

In [ ]:
auto_mpg_dataset_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
dataset_path = tf.keras.utils.get_file("/content/auto-mpg.data", auto_mpg_dataset_url)
dataset_path



Keras API를 이용한 보스턴 집값 회귀 실습_검증코드

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras import models,layers
import pandas as pd

"""* Step 1. Input tensor 와 Target tensor 준비(훈련데이터)"""

# 수강생 작성 코드
# 1. import 한 boston_housing API를 이용하여 boston_housing 데이터 셋을 다운로드 받으세요
(train_dataset, train_labels), (test_dataset, test_labels)= boston_housing.load_data()

columns=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO',
         'B', 'LSTAT']

train_dataset = pd.DataFrame(train_dataset, columns=columns)
#print(train_dataset)

#print(train_dataset.isna().sum())

#print(train_dataset.describe())

dataset = train_dataset.describe()
usu = dataset.transpose()

#print(usu)



"""* Step 2. 데이터의 전처리 """

# 수강생 작성 코드
# 1. train 데이터의 feature 별 평균값, 표준편차 값을 이용하여 정규화 작업을 진행하세요

def norm(x):
  normed_data = (x - usu['mean']) / usu['std']
  return normed_data

train_dataset = norm(train_dataset)

#print(train_dataset)

"""* Step 3. DNN(MLP) 모델 디자인"""

# 수강생 작성 코드
# 1. Sequential API를 이용하여 boston_housing 데이터 셋을 분석 하기 위한 MLP 모델을 디자인 하세요
model = models.Sequential()
model.add(layers.Dense(units=64, activation = 'relu', input_shape=(len(train_dataset.keys()) ,)))
model.add(layers.Dense(units=32, activation = 'relu'))
model.add(layers.Dense(units=1))


"""* Step 4. 모델의 학습 정보 설정"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 compile 메서드를 이용하여 학습을 위한 정보들을 설정하세요
#   - optimizer
#   - loss
#   - metrics : 체점 기준인 MAE 로 설정

model.compile(loss='mse',
              optimizer = 'rmsprop',
              metrics = ['mae'])


"""* Step 5. 모델에 input, target 데이터 연결 후 학습"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 fit 메서드를 이용하여 모델을 학습하세요
#   - fit 메서드의 verbose=2 로 설정 하세요
model.fit(x=train_dataset, y= train_labels,
          batch_size=16,
          epochs=100,
          validation_split = 0.2,
          verbose=2)


"""* 모델 제출 """

# 학습된 모델을 제출하기 위한 코드 입니다. 수정하지 마세요
model.save('my_model.h5')

57344/57026 [==============================] - 0s 0us/step
Epoch 1/100
21/21 - 1s - loss: 491.3745 - mae: 20.2228 - val_loss: 500.0025 - val_mae: 20.4300
Epoch 2/100
21/21 - 0s - loss: 375.2428 - mae: 17.2460 - val_loss: 369.7626 - val_mae: 17.1601
Epoch 3/100
21/21 - 0s - loss: 246.8032 - mae: 13.5048 - val_loss: 230.5961 - val_mae: 12.7227
Epoch 4/100
21/21 - 0s - loss: 132.8817 - mae: 9.2962 - val_loss: 127.1759 - val_mae: 8.6413
Epoch 5/100
21/21 - 0s - loss: 73.9208 - mae: 6.5032 - val_loss: 84.5669 - val_mae: 6.8867
Epoch 6/100
21/21 - 0s - loss: 51.3544 - mae: 5.1812 - val_loss: 63.2429 - val_mae: 5.8507
Epoch 7/100
21/21 - 0s - loss: 39.6361 - mae: 4.4010 - val_loss: 47.2416 - val_mae: 5.0540
Epoch 8/100
21/21 - 0s - loss: 31.7911 - mae: 3.7946 - val_loss: 37.2993 - val_mae: 4.4635
Epoch 9/100
21/21 - 0s - loss: 27.1076 - mae: 3.4341 - val_loss: 29.9961 - val_mae: 4.0149
Epoch 10/100
21/21 - 0s - loss: 23.8531 - mae: 3.2191 - val_loss: 25.9825 - val_mae: 3.7568
Epoch 11/100
21/

gpu 사용

In [ ]:
!nvidia-smi

Sat Jul  3 03:45:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

CNN 모델 구현 실습

In [ ]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
'''
print(train_images.shape)
print(train_labels.shape)

print(train_images[0])
print(train_labels[0])
'''

#입력 데이터 전처리
#train_images.max()
train_images = train_images / 255.
test_images = test_images / 255.

train_images = train_images.reshape(60000, 28, 28, 1)
test_images = test_images.reshape(10000, 28, 28, 1)

#라벨 데이터 전처리
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)


#CNN 모델 구현

from tensorflow.keras import models, layers

model = models.Sequential()

model.add(layers.Conv2D(
    filters=32, kernel_size=(3,3), 
    activation='relu',
    input_shape=(28,28,1)))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.Flatten())

model.add(layers.Dense(units=64, activation='relu'))
model.add(layers.Dense(units=10, activation='softmax'))

#model.summary()

#모델의 학습설정
#optimizer=['adam','adagrad','rmsprop']
# 

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy']
              )

model.fit(x=train_images, y=train_labels,
          epochs=15, batch_size=256,
          validation_split=0.2)

test_loss, test_accuracy = model.evaluate(x=test_images, y=test_labels)

Epoch 1/15
188/188 [==============================] - 2s 9ms/step - loss: 0.4212 - accuracy: 0.8672 - val_loss: 0.2796 - val_accuracy: 0.9084
Epoch 2/15
188/188 [==============================] - 1s 8ms/step - loss: 0.0952 - accuracy: 0.9703 - val_loss: 0.0725 - val_accuracy: 0.9783
Epoch 3/15
188/188 [==============================] - 1s 8ms/step - loss: 0.0589 - accuracy: 0.9821 - val_loss: 0.0575 - val_accuracy: 0.9835
Epoch 4/15
188/188 [==============================] - 1s 8ms/step - loss: 0.0431 - accuracy: 0.9864 - val_loss: 0.0469 - val_accuracy: 0.9856
Epoch 5/15
188/188 [==============================] - 1s 8ms/step - loss: 0.0331 - accuracy: 0.9892 - val_loss: 0.0437 - val_accuracy: 0.9872
Epoch 6/15
188/188 [==============================] - 1s 8ms/step - loss: 0.0273 - accuracy: 0.9911 - val_loss: 0.0459 - val_accuracy: 0.9862
Epoch 7/15
188/188 [==============================] - 2s 9ms/step - loss: 0.0214 - accuracy: 0.9930 - val_loss: 0.0375 - val_accuracy: 0.9890
Epoch 

CNN 활용한 f-mnist 실습

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

"""* Step 1. Input tensor 와 Target tensor 준비(훈련데이터)"""

# label 데이터의 각 value 에 해당하는 class name 정보
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 수강생 작성 코드
# 1. import 한 fashion_mnist API를 이용하여 fashion_mnist 데이터 셋을 다운로드 받으세요
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()


"""* Step 2. 입력데이터의 전처리 """

# 수강생 작성 코드
# 1. 3차원 형태(batch, hight, width)의 train, test feature 데이터를 3차원(batch, hight, width, chanel(1))으로 변경 하세요
# 2. feature 데이터를 [0, 1] 사이로 scailing을 수행하세요
train_images = train_images.reshape(60000, 28, 28, 1)
test_images = test_images.reshape(10000, 28, 28, 1)

train_images = train_images / 255.
test_images = test_images / 255.


# 수강생 작성 코드
# 1. 1차원 형태의(batch, ) class id 인 train, test label 데이터를
#    to_categorical API를 이용하여 one-hot-encoding 수행하여 2차원(batch, class_cnt) 으로 변경 하세요
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)



"""* Step3. CNN 모델 디자인"""

# 수강생 작성 코드
# 1. Sequential API를 이용하여 fashion_mnist 데이터 셋을 분석 하기 위한 CNN 모델을 디자인 하세요
from tensorflow.keras import layers, models
model = models.Sequential()
model.add(layers.Conv2D(
    filters=32, kernel_size=(3,3), 
    activation='relu',
    input_shape=(28,28,1)))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.Flatten())

model.add(layers.Dense(units=64, activation='relu'))
model.add(layers.Dense(units=10, activation='softmax'))


"""* Step 4. 모델의 학습 정보 설정"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 compile 메서드를 이용하여 학습을 위한 정보들을 설정하세요
#   - optimizer
#   - loss
#   - metrics : 체점 기준인 accuracy 로 설정

model.compile(optimizer='rmsprop',
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])



"""* Step 5. 모델에 input, target 데이터 연결 후 학습"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 fit 메서드를 이용하여 모델을 학습하세요
#   - fit 메서드의 verbose=2 로 설정 하세요
model.fit(x=train_images, y=train_labels,
          epochs=15, batch_size=256,
          validation_split=0.2,
          verbose=2)



4423680/4422102 [==============================] - 0s 0us/step
Epoch 1/15
188/188 - 2s - loss: 0.8131 - accuracy: 0.6975 - val_loss: 0.5412 - val_accuracy: 0.7977
Epoch 2/15
188/188 - 1s - loss: 0.4756 - accuracy: 0.8232 - val_loss: 0.5265 - val_accuracy: 0.8127
Epoch 3/15
188/188 - 1s - loss: 0.3933 - accuracy: 0.8561 - val_loss: 0.4586 - val_accuracy: 0.8250
Epoch 4/15
188/188 - 1s - loss: 0.3445 - accuracy: 0.8727 - val_loss: 0.3528 - val_accuracy: 0.8695
Epoch 5/15
188/188 - 1s - loss: 0.3107 - accuracy: 0.8864 - val_loss: 0.3251 - val_accuracy: 0.8799
Epoch 6/15
188/188 - 1s - loss: 0.2866 - accuracy: 0.8945 - val_loss: 0.3084 - val_accuracy: 0.8857
Epoch 7/15
188/188 - 1s - loss: 0.2668 - accuracy: 0.9015 - val_loss: 0.2815 - val_accuracy: 0.8972
Epoch 8/15
188/188 - 1s - loss: 0.2489 - accuracy: 0.9094 - val_loss: 0.2757 - val_accuracy: 0.9001
Epoch 9/15
188/188 - 1s - loss: 0.2355 - accuracy: 0.9137 - val_loss: 0.2845 - val_accuracy: 0.8933
Epoch 10/15
188/188 - 1s - loss: 0.22

CNN 활용한 cifar10 실습

In [ ]:
from tensorflow.keras.datasets import cifar10
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

#print(train_images.shape)
#print(train_labels.shape)



train_images = train_images / 255.
test_images = test_images / 255.

from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

from tensorflow.keras import models, layers

model = models.Sequential()
#(32,32,3)->(30,30,32)
model.add(layers.Conv2D(
    filters=32, kernel_size=(3,3), 
    activation='relu',
    input_shape=(32,32,3)))
#(30,30,64)->(15,15,32)
model.add(layers.MaxPool2D(
    pool_size=(2,2)))
#(15,15,32)->(13,13,64)
model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))
#(13,13,64)->(6,6,64)
model.add(layers.MaxPool2D(
    pool_size=(2,2)))
#(6,6,64)->(4,4,64)
model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.Flatten())

model.add(layers.Dense(units=64, activation='relu'))
model.add(layers.Dense(units=10, activation='softmax'))

model.summary()

#모델의 학습설정
#optimizer=['adam','adagrad','rmsprop']
# 

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy']
              )

model.fit(x=train_images, y=train_labels,
          epochs=20, batch_size=256,
          validation_split=0.2)

test_loss, test_accuracy = model.evaluate(x=test_images, y=test_labels)





Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_25 (Conv2D)           (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_26 (Conv2D)           (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_27 (Conv2D)           (None, 4, 4, 64)          36928     
_________________________________________________________________
flatten_8 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_16 (Dense)             (None, 64)              

CNN을 활용한 코드프레소-cifar10 실습

In [ ]:
import tensorflow as tf
import numpy as np
import requests
import io


"""* Step 1. Input tensor 와 Target tensor 준비(훈련데이터)"""

# label 데이터의 각 value 에 해당하는 class name 정보
cifar_label_name=['apple', 'beaver', 'bottle', 'butterfly', 'castle',
                  'clock', 'couch', 'leopard', 'rose', 'shark']

# 데이터 다운로드 url 경로
data_url = 'https://codepresso-online-platform-public.s3.ap-northeast-2.amazonaws.com/learning-resourse/Tensorflow+2.0+%EB%94%A5%EB%9F%AC%EB%8B%9D+%EC%99%84%EB%B2%BD+%EA%B0%80%EC%9D%B4%EB%93%9C/cifar-10-codepresso.npz'

# requests 라이브러리를 이용해 데이터 다운로드
response = requests.get(data_url)
response.raise_for_status()

# 다운로드 받은 데이터를 읽어 들여 Input tensor 와 Target tensor 준비
with np.load(io.BytesIO(response.content)) as cifar_10_codepresso_data:
  # 학습 이미지 데이터(np.ndarry, shape=(5000, 32, 32, 3))
  train_images = cifar_10_codepresso_data['train_images']
  # 학습 라벨 데이터(np.ndarry, shape=(5000, ))
  train_labels = cifar_10_codepresso_data['train_labels']
  
  # 테스트 이미지 데이터(np.ndarry, shape=(1000, 32, 32, 3))
  test_images = cifar_10_codepresso_data['test_images']
  # 테스트 라벨 데이터(np.ndarry, shape=(1000, ))
  test_labels = cifar_10_codepresso_data['test_labels']



"""* Step 2. 입력데이터의 전처리 """

# 수강생 작성 코드
# 1. feature 데이터를 [0, 1] 사이로 scailing을 수행하세요
train_images = train_images / 255.
test_images = test_images / 255.


# 수강생 작성 코드
# 1. 1차원 형태의(batch, ) class id 인 train, test label 데이터를
#    to_categorical API를 이용하여 one-hot-encoding 수행하여 2차원(batch, class_cnt) 으로 변경 하세요
from tensorflow.keras.utils import to_categorical
test_labels = to_categorical(test_labels)
train_labels = to_categorical(train_labels)


"""* Step3. CNN 모델 디자인"""

# 수강생 작성 코드
# 1. Sequential API를 이용하여 fashion_mnist 데이터 셋을 분석 하기 위한 CNN 모델을 디자인 하세요
#   - 오버피팅 발생 시 classification module에 layers.Dropout 레이어를 추가 하여 성능을 향상시켜 보세요
drop_rate=0.3

from tensorflow.keras import models, layers

model = models.Sequential()

model.add(layers.Conv2D(
    filters=32, kernel_size=(3,3), 
    activation='relu',
    input_shape=(32,32,3)))

model.add(layers.Dropout(drop_rate))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Dropout(drop_rate))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.MaxPool2D(
    pool_size=(2,2)))

model.add(layers.Dropout(drop_rate))

model.add(layers.Conv2D(
    filters=64, kernel_size=(3,3), 
    activation='relu'))

model.add(layers.Flatten())

model.add(layers.Dense(units=64, activation='relu'))
model.add(layers.Dense(units=10, activation='softmax'))


"""* Step 4. 모델의 학습 정보 설정"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 compile 메서드를 이용하여 학습을 위한 정보들을 설정하세요
#   - optimizer
#   - loss
#   - metrics : 체점 기준인 accuracy 로 설정

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


"""* Step 5. 모델에 input, target 데이터 연결 후 학습"""

# 수강생 작성 코드
# 1. tf.keras.Model 객체의 fit 메서드를 이용하여 모델을 학습하세요
#   - fit 메서드의 verbose=2 로 설정 하세요
model.fit(x=train_images, y=train_labels,
          epochs=40, batch_size=256,
          validation_split=0.2,
          verbose=2)

Epoch 1/40
16/16 - 1s - loss: 2.2285 - accuracy: 0.1805 - val_loss: 2.1648 - val_accuracy: 0.2610
Epoch 2/40
16/16 - 0s - loss: 1.9613 - accuracy: 0.2918 - val_loss: 1.9859 - val_accuracy: 0.2940
Epoch 3/40
16/16 - 0s - loss: 1.8421 - accuracy: 0.3453 - val_loss: 1.8908 - val_accuracy: 0.3480
Epoch 4/40
16/16 - 0s - loss: 1.7327 - accuracy: 0.3915 - val_loss: 1.9576 - val_accuracy: 0.2670
Epoch 5/40
16/16 - 0s - loss: 1.7085 - accuracy: 0.3927 - val_loss: 1.8058 - val_accuracy: 0.4120
Epoch 6/40
16/16 - 0s - loss: 1.5925 - accuracy: 0.4340 - val_loss: 1.7392 - val_accuracy: 0.4360
Epoch 7/40
16/16 - 0s - loss: 1.5727 - accuracy: 0.4515 - val_loss: 1.7386 - val_accuracy: 0.4610
Epoch 8/40
16/16 - 0s - loss: 1.5055 - accuracy: 0.4720 - val_loss: 1.6378 - val_accuracy: 0.4460
Epoch 9/40
16/16 - 0s - loss: 1.4718 - accuracy: 0.4857 - val_loss: 1.6014 - val_accuracy: 0.5020
Epoch 10/40
16/16 - 0s - loss: 1.4125 - accuracy: 0.5070 - val_loss: 1.5497 - val_accuracy: 0.5110
Epoch 11/40
16/16 -